/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedMoreRouteImport } from './routes/_authenticated/more'
import { Route as AuthenticatedImpactRouteImport } from './routes/_authenticated/impact'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedDirectoryRouteImport } from './routes/_authenticated/directory'
import { Route as AuthenticatedBusinessesRouteImport } from './routes/_authenticated/businesses'
import { Route as AuthenticatedImpactIndexRouteImport } from './routes/_authenticated/impact.index'
import { Route as AuthenticatedImpactVolunteerRouteImport } from './routes/_authenticated/impact.volunteer'
import { Route as AuthenticatedImpactHistoryRouteImport } from './routes/_authenticated/impact.history'
import { Route as AuthenticatedImpactDonateRouteImport } from './routes/_authenticated/impact.donate'
import { Route as AuthenticatedImpactActivityRouteImport } from './routes/_authenticated/impact.activity'
import { Route as AuthenticatedGroupsGroupIdRouteImport } from './routes/_authenticated/groups.$groupId'
import { Route as AuthenticatedEventsEventIdRouteImport } from './routes/_authenticated/events.$eventId'
import { Route as AuthenticatedDirectoryMemberIdRouteImport } from './routes/_authenticated/directory.$memberId'
import { Route as AuthenticatedBusinessesBusinessIdRouteImport } from './routes/_authenticated/businesses.$businessId'
import { Route as AuthenticatedImpactOpportunityOpportunityIdRouteImport } from './routes/_authenticated/impact.opportunity.$opportunityId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMoreRoute = AuthenticatedMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImpactRoute = AuthenticatedImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDirectoryRoute = AuthenticatedDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusinessesRoute = AuthenticatedBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImpactIndexRoute =
  AuthenticatedImpactIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedImpactRoute,
  } as any)
const AuthenticatedImpactVolunteerRoute =
  AuthenticatedImpactVolunteerRouteImport.update({
    id: '/volunteer',
    path: '/volunteer',
    getParentRoute: () => AuthenticatedImpactRoute,
  } as any)
const AuthenticatedImpactHistoryRoute =
  AuthenticatedImpactHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedImpactRoute,
  } as any)
const AuthenticatedImpactDonateRoute =
  AuthenticatedImpactDonateRouteImport.update({
    id: '/donate',
    path: '/donate',
    getParentRoute: () => AuthenticatedImpactRoute,
  } as any)
const AuthenticatedImpactActivityRoute =
  AuthenticatedImpactActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedImpactRoute,
  } as any)
const AuthenticatedGroupsGroupIdRoute =
  AuthenticatedGroupsGroupIdRouteImport.update({
    id: '/$groupId',
    path: '/$groupId',
    getParentRoute: () => AuthenticatedGroupsRoute,
  } as any)
const AuthenticatedEventsEventIdRoute =
  AuthenticatedEventsEventIdRouteImport.update({
    id: '/$eventId',
    path: '/$eventId',
    getParentRoute: () => AuthenticatedEventsRoute,
  } as any)
const AuthenticatedDirectoryMemberIdRoute =
  AuthenticatedDirectoryMemberIdRouteImport.update({
    id: '/$memberId',
    path: '/$memberId',
    getParentRoute: () => AuthenticatedDirectoryRoute,
  } as any)
const AuthenticatedBusinessesBusinessIdRoute =
  AuthenticatedBusinessesBusinessIdRouteImport.update({
    id: '/$businessId',
    path: '/$businessId',
    getParentRoute: () => AuthenticatedBusinessesRoute,
  } as any)
const AuthenticatedImpactOpportunityOpportunityIdRoute =
  AuthenticatedImpactOpportunityOpportunityIdRouteImport.update({
    id: '/opportunity/$opportunityId',
    path: '/opportunity/$opportunityId',
    getParentRoute: () => AuthenticatedImpactRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/businesses': typeof AuthenticatedBusinessesRouteWithChildren
  '/directory': typeof AuthenticatedDirectoryRouteWithChildren
  '/events': typeof AuthenticatedEventsRouteWithChildren
  '/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/impact': typeof AuthenticatedImpactRouteWithChildren
  '/more': typeof AuthenticatedMoreRoute
  '/businesses/$businessId': typeof AuthenticatedBusinessesBusinessIdRoute
  '/directory/$memberId': typeof AuthenticatedDirectoryMemberIdRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/impact/activity': typeof AuthenticatedImpactActivityRoute
  '/impact/donate': typeof AuthenticatedImpactDonateRoute
  '/impact/history': typeof AuthenticatedImpactHistoryRoute
  '/impact/volunteer': typeof AuthenticatedImpactVolunteerRoute
  '/impact/': typeof AuthenticatedImpactIndexRoute
  '/impact/opportunity/$opportunityId': typeof AuthenticatedImpactOpportunityOpportunityIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/businesses': typeof AuthenticatedBusinessesRouteWithChildren
  '/directory': typeof AuthenticatedDirectoryRouteWithChildren
  '/events': typeof AuthenticatedEventsRouteWithChildren
  '/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/more': typeof AuthenticatedMoreRoute
  '/': typeof AuthenticatedIndexRoute
  '/businesses/$businessId': typeof AuthenticatedBusinessesBusinessIdRoute
  '/directory/$memberId': typeof AuthenticatedDirectoryMemberIdRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/impact/activity': typeof AuthenticatedImpactActivityRoute
  '/impact/donate': typeof AuthenticatedImpactDonateRoute
  '/impact/history': typeof AuthenticatedImpactHistoryRoute
  '/impact/volunteer': typeof AuthenticatedImpactVolunteerRoute
  '/impact': typeof AuthenticatedImpactIndexRoute
  '/impact/opportunity/$opportunityId': typeof AuthenticatedImpactOpportunityOpportunityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/businesses': typeof AuthenticatedBusinessesRouteWithChildren
  '/_authenticated/directory': typeof AuthenticatedDirectoryRouteWithChildren
  '/_authenticated/events': typeof AuthenticatedEventsRouteWithChildren
  '/_authenticated/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/_authenticated/impact': typeof AuthenticatedImpactRouteWithChildren
  '/_authenticated/more': typeof AuthenticatedMoreRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/businesses/$businessId': typeof AuthenticatedBusinessesBusinessIdRoute
  '/_authenticated/directory/$memberId': typeof AuthenticatedDirectoryMemberIdRoute
  '/_authenticated/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/_authenticated/groups/$groupId': typeof AuthenticatedGroupsGroupIdRoute
  '/_authenticated/impact/activity': typeof AuthenticatedImpactActivityRoute
  '/_authenticated/impact/donate': typeof AuthenticatedImpactDonateRoute
  '/_authenticated/impact/history': typeof AuthenticatedImpactHistoryRoute
  '/_authenticated/impact/volunteer': typeof AuthenticatedImpactVolunteerRoute
  '/_authenticated/impact/': typeof AuthenticatedImpactIndexRoute
  '/_authenticated/impact/opportunity/$opportunityId': typeof AuthenticatedImpactOpportunityOpportunityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/businesses'
    | '/directory'
    | '/events'
    | '/groups'
    | '/impact'
    | '/more'
    | '/businesses/$businessId'
    | '/directory/$memberId'
    | '/events/$eventId'
    | '/groups/$groupId'
    | '/impact/activity'
    | '/impact/donate'
    | '/impact/history'
    | '/impact/volunteer'
    | '/impact/'
    | '/impact/opportunity/$opportunityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/businesses'
    | '/directory'
    | '/events'
    | '/groups'
    | '/more'
    | '/'
    | '/businesses/$businessId'
    | '/directory/$memberId'
    | '/events/$eventId'
    | '/groups/$groupId'
    | '/impact/activity'
    | '/impact/donate'
    | '/impact/history'
    | '/impact/volunteer'
    | '/impact'
    | '/impact/opportunity/$opportunityId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/businesses'
    | '/_authenticated/directory'
    | '/_authenticated/events'
    | '/_authenticated/groups'
    | '/_authenticated/impact'
    | '/_authenticated/more'
    | '/_authenticated/'
    | '/_authenticated/businesses/$businessId'
    | '/_authenticated/directory/$memberId'
    | '/_authenticated/events/$eventId'
    | '/_authenticated/groups/$groupId'
    | '/_authenticated/impact/activity'
    | '/_authenticated/impact/donate'
    | '/_authenticated/impact/history'
    | '/_authenticated/impact/volunteer'
    | '/_authenticated/impact/'
    | '/_authenticated/impact/opportunity/$opportunityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/more': {
      id: '/_authenticated/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AuthenticatedMoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impact': {
      id: '/_authenticated/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof AuthenticatedImpactRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/directory': {
      id: '/_authenticated/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof AuthenticatedDirectoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/businesses': {
      id: '/_authenticated/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof AuthenticatedBusinessesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impact/': {
      id: '/_authenticated/impact/'
      path: '/'
      fullPath: '/impact/'
      preLoaderRoute: typeof AuthenticatedImpactIndexRouteImport
      parentRoute: typeof AuthenticatedImpactRoute
    }
    '/_authenticated/impact/volunteer': {
      id: '/_authenticated/impact/volunteer'
      path: '/volunteer'
      fullPath: '/impact/volunteer'
      preLoaderRoute: typeof AuthenticatedImpactVolunteerRouteImport
      parentRoute: typeof AuthenticatedImpactRoute
    }
    '/_authenticated/impact/history': {
      id: '/_authenticated/impact/history'
      path: '/history'
      fullPath: '/impact/history'
      preLoaderRoute: typeof AuthenticatedImpactHistoryRouteImport
      parentRoute: typeof AuthenticatedImpactRoute
    }
    '/_authenticated/impact/donate': {
      id: '/_authenticated/impact/donate'
      path: '/donate'
      fullPath: '/impact/donate'
      preLoaderRoute: typeof AuthenticatedImpactDonateRouteImport
      parentRoute: typeof AuthenticatedImpactRoute
    }
    '/_authenticated/impact/activity': {
      id: '/_authenticated/impact/activity'
      path: '/activity'
      fullPath: '/impact/activity'
      preLoaderRoute: typeof AuthenticatedImpactActivityRouteImport
      parentRoute: typeof AuthenticatedImpactRoute
    }
    '/_authenticated/groups/$groupId': {
      id: '/_authenticated/groups/$groupId'
      path: '/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AuthenticatedGroupsGroupIdRouteImport
      parentRoute: typeof AuthenticatedGroupsRoute
    }
    '/_authenticated/events/$eventId': {
      id: '/_authenticated/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthenticatedEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedEventsRoute
    }
    '/_authenticated/directory/$memberId': {
      id: '/_authenticated/directory/$memberId'
      path: '/$memberId'
      fullPath: '/directory/$memberId'
      preLoaderRoute: typeof AuthenticatedDirectoryMemberIdRouteImport
      parentRoute: typeof AuthenticatedDirectoryRoute
    }
    '/_authenticated/businesses/$businessId': {
      id: '/_authenticated/businesses/$businessId'
      path: '/$businessId'
      fullPath: '/businesses/$businessId'
      preLoaderRoute: typeof AuthenticatedBusinessesBusinessIdRouteImport
      parentRoute: typeof AuthenticatedBusinessesRoute
    }
    '/_authenticated/impact/opportunity/$opportunityId': {
      id: '/_authenticated/impact/opportunity/$opportunityId'
      path: '/opportunity/$opportunityId'
      fullPath: '/impact/opportunity/$opportunityId'
      preLoaderRoute: typeof AuthenticatedImpactOpportunityOpportunityIdRouteImport
      parentRoute: typeof AuthenticatedImpactRoute
    }
  }
}

interface AuthenticatedBusinessesRouteChildren {
  AuthenticatedBusinessesBusinessIdRoute: typeof AuthenticatedBusinessesBusinessIdRoute
}

const AuthenticatedBusinessesRouteChildren: AuthenticatedBusinessesRouteChildren =
  {
    AuthenticatedBusinessesBusinessIdRoute:
      AuthenticatedBusinessesBusinessIdRoute,
  }

const AuthenticatedBusinessesRouteWithChildren =
  AuthenticatedBusinessesRoute._addFileChildren(
    AuthenticatedBusinessesRouteChildren,
  )

interface AuthenticatedDirectoryRouteChildren {
  AuthenticatedDirectoryMemberIdRoute: typeof AuthenticatedDirectoryMemberIdRoute
}

const AuthenticatedDirectoryRouteChildren: AuthenticatedDirectoryRouteChildren =
  {
    AuthenticatedDirectoryMemberIdRoute: AuthenticatedDirectoryMemberIdRoute,
  }

const AuthenticatedDirectoryRouteWithChildren =
  AuthenticatedDirectoryRoute._addFileChildren(
    AuthenticatedDirectoryRouteChildren,
  )

interface AuthenticatedEventsRouteChildren {
  AuthenticatedEventsEventIdRoute: typeof AuthenticatedEventsEventIdRoute
}

const AuthenticatedEventsRouteChildren: AuthenticatedEventsRouteChildren = {
  AuthenticatedEventsEventIdRoute: AuthenticatedEventsEventIdRoute,
}

const AuthenticatedEventsRouteWithChildren =
  AuthenticatedEventsRoute._addFileChildren(AuthenticatedEventsRouteChildren)

interface AuthenticatedGroupsRouteChildren {
  AuthenticatedGroupsGroupIdRoute: typeof AuthenticatedGroupsGroupIdRoute
}

const AuthenticatedGroupsRouteChildren: AuthenticatedGroupsRouteChildren = {
  AuthenticatedGroupsGroupIdRoute: AuthenticatedGroupsGroupIdRoute,
}

const AuthenticatedGroupsRouteWithChildren =
  AuthenticatedGroupsRoute._addFileChildren(AuthenticatedGroupsRouteChildren)

interface AuthenticatedImpactRouteChildren {
  AuthenticatedImpactActivityRoute: typeof AuthenticatedImpactActivityRoute
  AuthenticatedImpactDonateRoute: typeof AuthenticatedImpactDonateRoute
  AuthenticatedImpactHistoryRoute: typeof AuthenticatedImpactHistoryRoute
  AuthenticatedImpactVolunteerRoute: typeof AuthenticatedImpactVolunteerRoute
  AuthenticatedImpactIndexRoute: typeof AuthenticatedImpactIndexRoute
  AuthenticatedImpactOpportunityOpportunityIdRoute: typeof AuthenticatedImpactOpportunityOpportunityIdRoute
}

const AuthenticatedImpactRouteChildren: AuthenticatedImpactRouteChildren = {
  AuthenticatedImpactActivityRoute: AuthenticatedImpactActivityRoute,
  AuthenticatedImpactDonateRoute: AuthenticatedImpactDonateRoute,
  AuthenticatedImpactHistoryRoute: AuthenticatedImpactHistoryRoute,
  AuthenticatedImpactVolunteerRoute: AuthenticatedImpactVolunteerRoute,
  AuthenticatedImpactIndexRoute: AuthenticatedImpactIndexRoute,
  AuthenticatedImpactOpportunityOpportunityIdRoute:
    AuthenticatedImpactOpportunityOpportunityIdRoute,
}

const AuthenticatedImpactRouteWithChildren =
  AuthenticatedImpactRoute._addFileChildren(AuthenticatedImpactRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBusinessesRoute: typeof AuthenticatedBusinessesRouteWithChildren
  AuthenticatedDirectoryRoute: typeof AuthenticatedDirectoryRouteWithChildren
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRouteWithChildren
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRouteWithChildren
  AuthenticatedImpactRoute: typeof AuthenticatedImpactRouteWithChildren
  AuthenticatedMoreRoute: typeof AuthenticatedMoreRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBusinessesRoute: AuthenticatedBusinessesRouteWithChildren,
  AuthenticatedDirectoryRoute: AuthenticatedDirectoryRouteWithChildren,
  AuthenticatedEventsRoute: AuthenticatedEventsRouteWithChildren,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRouteWithChildren,
  AuthenticatedImpactRoute: AuthenticatedImpactRouteWithChildren,
  AuthenticatedMoreRoute: AuthenticatedMoreRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
